---
- hosts: all

  tasks:

  ###########################################
  # General
  ###########################################
  - name: Install usefull system tools
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - vim
      - curl
      - htop
      - git
      - tig
      - ncdu

  ############################################
  # Database software
  ############################################

  - name: Install Postgresql
    apt: name={{item}}
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2

  - name: Create databases
    sudo: yes
    sudo_user: postgres
    postgresql_db: name=nextbus

  - name: Create database user
    sudo: yes
    sudo_user: postgres
    postgresql_user: name=nextbus password=changeme state=present role_attr_flags=NOSUPERUSER,CREATEDB

  - name: Add permissions on nextbus
    sudo: yes
    sudo_user: postgres
    postgresql_user: user=nextbus db=nextbus priv=ALL


  ############################################
  # Nextbus-stats specific
  ############################################

  # Redis server
  - name: Install redis server
    apt: name=redis-server state=latest

  - name: Start redis server
    service: name=redis-server state=started enabled=true

  # Node.js
  - name: Node.js/npm
    apt: name={{ item }} state=present
    with_items:
      - nodejs-legacy
      - npm

  - name: nodemon (via npm)
    npm: name={{ item }} global=yes
    with_items:
      - bower
      # We need JS/CSS compressors globally so they can be executed outside of virtualenv
      - yuglify


  # Python / Virtualenv
  - name: Install pip/python ffi/ssl libs (for urllib3 warning)
    apt: name={{ item }} state=latest
    with_items:
      - python-pip
      - python-dev
      - libffi-dev
      - libssl-dev

  - name: Install virtualenv/wrapper
    pip: name={{ item }}
    with_items:
      - virtualenv
      - virtualenvwrapper

  - name: Insert virtualenvwrapper script into bashrc
    lineinfile:
      dest=/home/vagrant/.bashrc
      line="source /usr/local/bin/virtualenvwrapper.sh"
      state=present
      insertafter=EOF